/*
 *  Copyright (C) 2026 Liam Girdwood
 */

#ifndef _KERNELS_H
#define _KERNELS_H

const char *opencl_source_string =
	"__kernel void add(__global float *a, __global const float *b, __global const float *c, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] = b[i] + c[i];\n"
	"}\n"
	"__kernel void add_sig(__global float *a, __global const float *b, __global const float *c, __global const uint *s, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems && s[i]) a[i] = b[i] + c[i];\n"
	"}\n"
	"__kernel void subtract(__global float *a, __global const float *b, __global const float *c, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] = b[i] - c[i];\n"
	"}\n"
	"__kernel void subtract_sig(__global float *a, __global const float *b, __global const float *c, __global const uint *s, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems && s[i]) a[i] = b[i] - c[i];\n"
	"}\n"
	"__kernel void add_value(__global float *a, float value, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] += value;\n"
	"}\n"
	"__kernel void subtract_value(__global float *a, float value, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] -= value;\n"
	"}\n"
	"__kernel void mult_value(__global float *a, float value, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] *= value;\n"
	"}\n"
	"__kernel void reset_value(__global float *a, float value, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] = value;\n"
	"}\n"
	"__kernel void set_sig_value(__global uint *a, uint value, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] = value;\n"
	"}\n"
	"__kernel void set_value_sig(__global float *a, __global const uint *s, float value, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems && s[i]) a[i] = value;\n"
	"}\n"
	"__kernel void clear_negative(__global float *a, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems && a[i] < 0.0f) a[i] = 0.0f;\n"
	"}\n"
	"__kernel void abs_k(__global float *a, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] = fabs(a[i]);\n"
	"}\n"
	"__kernel void copy_sig(__global float *dest, __global const float *src, __global const uint *sig, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) dest[i] = sig[i] ? src[i] : 0.0f;\n"
	"}\n"
	"__kernel void mult_add_k(__global float *dest, __global const float *a, __global const float *b, float c, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) dest[i] = a[i] + b[i] * c;\n"
	"}\n"
	"__kernel void mult_subtract_k(__global float *dest, __global const float *a, __global const float *b, float c, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) dest[i] = a[i] - b[i] * c;\n"
	"}\n"
	"__kernel void anscombe_k(__global float *a, float gain, float bias, float readout, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) {\n"
	"        float tmp = gain * (a[i] - bias) + (3.0f/8.0f) + readout*readout;\n"
	"        a[i] = (tmp > 0.0f) ? 2.0f * sqrt(tmp) : 0.0f;\n"
	"    }\n"
	"}\n"
	"__kernel void normalise_k(__global float *a, float min, float max, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) a[i] = (a[i] - min) * max;\n"
	"}\n"
	"__kernel void new_significance(__global const float *a, __global uint *s, float sigma, int elems) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < elems) s[i] = (fabs(a[i]) > sigma) ? 1 : 0;\n"
	"}\n"
	"__kernel void atrous_conv_1d(__global float *dest, __global const float *src, __global const float *mask, int width, int mask_len, int offset) {\n"
	"    int i = get_global_id(0);\n"
	"    if (i < width) {\n"
	"        int mh = mask_len / 2;\n"
	"        float sum = 0.0f;\n"
	"        for (int m = -mh; m <= mh; m++) {\n"
	"            int si = i + m * offset;\n"
	"            if (si < 0) si = -si; else if (si >= width) si = 2*width - 2 - si;\n"
	"            sum += src[si] * mask[m + mh];\n"
	"        }\n"
	"        dest[i] = sum;\n"
	"    }\n"
	"}\n"
	"__kernel void atrous_conv_2d(__global float *dest, __global const float *src, __global const float *mask, int width, int height, int mask_len, int offset) {\n"
	"    int x = get_global_id(0);\n"
	"    int y = get_global_id(1);\n"
	"    if (x < width && y < height) {\n"
	"        int mh = mask_len / 2;\n"
	"        float sum = 0.0f;\n"
	"        for (int my = -mh; my <= mh; my++) {\n"
	"            int sy = y + my * offset;\n"
	"            if (sy < 0) sy = -sy; else if (sy >= height) sy = 2*height - 2 - sy;\n"
	"            for (int mx = -mh; mx <= mh; mx++) {\n"
	"                int sx = x + mx * offset;\n"
	"                if (sx < 0) sx = -sx; else if (sx >= width) sx = 2*width - 2 - sx;\n"
	"                sum += src[sy * width + sx] * mask[(my + mh) * mask_len + (mx + mh)];\n"
	"            }\n"
	"        }\n"
	"        dest[y * width + x] = sum;\n"
	"    }\n"
	"}\n";

#endif /* _KERNELS_H */
